### ISSUE TITLE
Feature request: forward, backward, refresh, and enable desktop site buttons. 

### ISSUE THREAD

**Issue by Arkuarius** [KristhianX/essential-buttons-toolbar#1]
Hello, I like the idea of this toolbar. But I feel like there isn't much use for it. Could you please consider adding forward, backward, refresh page, and enable desktop site buttons? Those are more useful. I hate how I have to click on Firefox Android's menu button and then click on the forward, backward, and refresh buttons when they should be displayed all the time.

There is an add-on that adds a toolbar with those buttons to Kiwi Browser, and it's awesome. It would be great if Firefox had something similar.
![Screenshot_2023-12-16-22-45-06-066_com kiwibrowser browser-edit](https://github.com/KristhianX/essential-buttons-toolbar/assets/102014881/ba7a7eff-347c-419a-9bcd-ac291afcfc8a)

**Comment by KristhianX** [comment]
Hi, thanks for submitting a feature request! 

This add-on is still in development and was initially created to provide a standard home button. However, as you mentioned, it makes sense to include more useful buttons. 

The forward, backward, and reload buttons are easy to implement, and I'll add them in the next update. Regarding the toggle desktop site button, there is no API for that, so it will take some time to implement.

**Comment by Arkuarius** [comment]
> Regarding the toggle desktop site button, there is no API for that, so it will take some time to implement.

Actually, another add-on for Firefox called [Simple Gestures](https://github.com/utubo/firefox-simple_gesture) can enable desktop site. I don't know how this add-on does it, maybe you could learn how by researching its source code, but it is definitely possible even without an API it seems.

Regardless, I'm glad you're going to add those buttons soon enough! I can't wait for the update, cause once I get those buttons on Firefox/Iceraven on Android, Firefox will be a flawless experience for me!

**Comment by KristhianX** [comment]
The add-on has just been updated with 'go back,' 'go forward,' and 'reload' buttons. Hopefully, automatic updates should be working now. Alternatively, you can go to the store and reinstall the add-on to force the update; settings won't be lost.

By default, those buttons will be disabled. You need to toggle them on the settings page and move them to your desired position.

Regarding the toggle desktop site button, thanks for sharing that add-on; it is really good and will be a good starting point. 

I hope you enjoy the update; the main objective of this add-on is to help users adapt to Firefox and continue using it. The more users there are, the better the support from website developers will be.

**Comment by Arkuarius** [comment]
Awesome! Thank you so much. I feel like my entire Iceraven on Android experience is complete now!

**Comment by KristhianX** [comment]
Hi! The add-on has been updated and now includes a toggle desktop site button. Thanks for your suggestion. Please update, enable it, and test it.

Have a nice day!

**Comment by Arkuarius** [comment]
Yes, it does work! I've tried this on MyAnimeList.net, and it switched to the desktop side immediately.

However, when I clicked on the button again to revert to the mobile website, it just didn't work, it remained in the desktop website and just reloaded the page. I suppose that could be just a limitation of enabling desktop site using the add-on rather than Firefox itself, so there might not be much you could do. But it's still an issue I feel like you should be made aware of.

I hope you're having a good new year, so far! :D

**Comment by KristhianX** [comment]
Hi! Thank you for your kind words. I also hope you are doing great.

Thanks for your prompt response and for testing the new button. In my tests, the button worked fine. Please let me know if you encounter a reproducible error.

Keep in mind that the button will only reload your current tab. Toolbars in other open tabs will update the button icon but won't reload their tabs. So, if you toggle the button in one tab and go to another, you will have to manually reload it. Additionally, if you toggle the button in one tab, switch to another tab, and toggle the button there, you will need to go back to the previous tab and reload it manually.

Please let me know if you have any questions or suggestions.
