### ISSUE TITLE
Call `window.stop()` for some buttons

### ISSUE THREAD

**Issue by MilaMurry** [KristhianX/essential-buttons-toolbar#11]
I think the `go back`, `go forward`, `reload page`, `home` and `close tab` should call `window.stop()` or equivalents beforehand as soon as a user click it. That is, don't wait for a page or javascripts to complete their stuff. Currently, they behave the same as the browser's. Most of the time I don't care anymore or maybe the page is [too laggy](https://odysee.com/) and I just want to either go back or close the tab.

**Comment by KristhianX** [comment]
Good suggestion. I'll add this in the next update.

**Comment by KristhianX** [comment]
Hi! I hope you are doing great.

I've included this suggestion in the new version (1.7), and I've also applied it to the 'open with' and 'close all tabs' buttons.

Please let me know if the behavior is better now. Thanks!

**Comment by MilaMurry** [comment]
I am doing just fine, thank you. Hope you too.

It makes some pages much smoother now, at least a little bit.

The buttons seem synchronous by default, which means a button doesn't cancel the other pending buttons. When I go to odysee.com, I can click some buttons and they are all highlighted.
Hopefully there will be some sort of gatekeepers or cancelers in the future. It is a minor issue so not a big deal.
