### ISSUE TITLE
[Feature request] Share button

### ISSUE THREAD

**Issue by MilaMurry** [KristhianX/essential-buttons-toolbar#14]
Well, I think I use the share button quite often, so it's good to have something quicker.
It can be done like this:
```javascript
navigator.share({
  title: document.title,
  url: window.location.href
});
```

You can use the [Intent Intercept](https://f-droid.org/en/packages/de.k3b.android.intentintercept/) app to debug it.

**Comment by KristhianX** [comment]
Thanks for providing the link to the app. It will be added in a future update

**Comment by mglh** [comment]
I second this feature request.

**Comment by C-O-D** [comment]
I love this add-on and am so grateful that it exists and that's the only thing i'm really missing so far, a share button...

**Comment by KristhianX** [comment]
The 'Share URL' button has been added in the new 1.9.3 version, already available on the store.

**Comment by C-O-D** [comment]
Wow, thank you very much! 👍
