### ISSUE TITLE
Having access to Firefox's Homepage (or Home Screen)

### ISSUE THREAD

**Issue by Cr8zyIvan** [KristhianX/essential-buttons-toolbar#19]
In the "New Tab" Function, I'd like to assign Firefox's builtin Homepage (or Home Screen, depending on which article you read). The default "Homepage" where you can see your custom set sections: Shortcuts, Jump back in, Recent bookmarks, etc.

Unless there's a way to do so that I haven't found, I've only managed to get to the tabliss homepage and the about:blank, wich is... well, blank.

Thanks.

**Comment by KristhianX** [comment]
Hi! Unfortunately, the Firefox homepage on Android is not a tab and does not have a URL. It is part of the browser UI and cannot be accessed by add-ons.

I'll add a homepage replacement. Initially, it will only have the ability to add 'top sites.' Please see issue #6. Hopefully, I will include this in the next update.

**Comment by KristhianX** [comment]
I am closing this issue. Feel free to open any other issues or feature requests. Have a nice day!

**Comment by Cr8zyIvan** [comment]
That's what I suspected, but I figured I'd ask. Thank you for the reply!
