### ISSUE TITLE
reopen last tab

### ISSUE THREAD

**Issue by samesdat** [KristhianX/essential-buttons-toolbar#2]
Hi! I find the toolbar very helpful! Could you add a button "reopen last tab" (ctrl shift t)? I have to click 4 times minimum to reopen last closed tab, and I often use it. Simple gestures addon doesn't have this function and I didn't find it for Firefox Android.

**Comment by KristhianX** [comment]
Hi! Thank you for your kind words and your feature request. 

The easiest way to implement this is by tracking the URL of the last tab closed using this add-on and then having the 'reopen last tab' button open it in a new tab. 

Due to missing functionality in some Firefox Android APIs, I believe this is currently the best approach.

**Comment by KristhianX** [comment]
![Screenshot_20231228-220025](https://github.com/KristhianX/essential-buttons-toolbar/assets/46209998/e3ba8f21-ce64-408f-923e-2d2a6a7e94fa)

Version 1.4.3 has been released with the new button. I've decided to call it 'Undo Close Tab.' It will be disabled by default, so please go to settings, enable it, and move it to your desired position. Let me know if you have any questions or suggestions.

Release notes for 1.4.3
- New button: 'Undo Close Tab.' It opens a new tab with the last URL closed using the close tab button of this add-on. Once used, it will discard the saved URL to avoid opening duplicate tabs.

**Comment by samesdat** [comment]
I'm excited! Thanks for this extremely fast implementation! It didn't work once or twice though. I'll see when this case occurs.

**Comment by samesdat** [comment]
Sadly, it doesn't work any more. 
Yesterday, it sometimes reopened tabs. I tried to reopen newly opened (and then closed) tabs as well as tabs which opened together with the browser from the last session which I closed than and tried to reopen. I didn't find a pattern which tabs open and which not.
Today no single closed tabs reopened.

**Comment by KristhianX** [comment]
Hi! That behavior seems unusual. I conducted some tests, and it is working as expected, even after restarting the browser or the phone.

Let me walk you through the logic of this button's behavior, so we can pinpoint exactly in what cases it might be failing for you:

The 'close tab' button saves the tab URL to local storage (or updates it if there was a previous URL saved) and then closes the tab. This action results in the loss of the navigation history for that tab. The restored tab won't have that history.

When the 'undo close tab' button is pressed, it retrieves the URL saved by the last 'close tab' button press and creates a new tab with that URL. After creating the tab, it clears the URL from local storage to prevent opening a duplicate of the already restored URL if pressed again. In that case it won't do anything.

It's important to note that tabs closed automatically by the browser or in the tab list, as well as tabs closed by other add-ons, won't be detected. I haven't implemented a listener for removed tabs. 

While it's possible, the tabs API on Firefox Android lacks some functionality needed to create a listener that accurately detects all the events and data for this function. I hope that in the future, Firefox developers will address this support issue.

If you are closing tabs from the tab list, please use the undo button that appears there. 

![Screenshot_20231230-131526](https://github.com/KristhianX/essential-buttons-toolbar/assets/46209998/077cdb04-5ae4-42f4-8aeb-31716f174313)

Please let me know if you still encounter issues after using the buttons accordingly to this information.

**Comment by samesdat** [comment]
Thank you for the detailed explanation. I'm closing tabs via a gesture of the add-on "Simple gestures". That's why it doesn't work as you pointed out that it doesn't work when closing tabs via another add-on. Obviously, "Simple gestures" closes tabs in another way than the closing button on your toolbar.

**Comment by KristhianX** [comment]
That is a great add-on. I know it allows for custom JavaScript as well as sending messages to other add-ons. Maybe we can get it working.

Also, I will try to implement a listener and see how well it works, but that will have to wait until next year :)

**Comment by samesdat** [comment]
> wait until next year :)

Really?! Two days? :))

Serious: Thank you a lot. Do not hurry, I'm fine: I deleted the gesture for closing tab in Simple gestures and I'm now closing all tabs via close button on your toolbar.

**Comment by KristhianX** [comment]
There is an issue with the 'Undo Close Tab(s)' button in the new version. The fix will be included in the next version. I am addressing other bugs to ship everything in the same update.
