### ISSUE TITLE
add tab counter button

### ISSUE THREAD

**Issue by sheikh-azharuddin** [KristhianX/essential-buttons-toolbar#21]
Is it possible to add a tab counter button or an option which would trigger or open the manage tabs page of firefox.. currently this is the only thing for which I have to keep firefox toolbar at bottom

**Comment by KristhianX** [comment]
Hi! thanks for your suggestion.

Opening the Firefox tab menu is not possible, as add-ons do not have access to the browser UI.

A tab menu button has been requested in issue #7. I need to make some research about it, and if it is functional, I am still unsure about the approach – whether to make it a list of tabs or a horizontal tab bar. If you believe the behavior you want is compatible with the tab menu in that issue, please feel free to share your suggestion there.

I will add the question label for now, as I need more information about the feature you are requesting.
