### ISSUE TITLE
focus on search bar

### ISSUE THREAD

**Issue by eblantiy** [KristhianX/essential-buttons-toolbar#22]
it would be nice if you could add the same behavior as in firefox when opening new tab. it's insignificant, but it would spare one extra click.

**Comment by KristhianX** [comment]
Hi! Thanks for using the add-on and providing your feedback.

Unfortunately, it is not possible since add-ons do not have access to the browser UI, including the address bar.

Are you using a search engine as the new tab URL and hoping to have the search bar focused?
