### ISSUE TITLE
Blank page as new page does not work

### ISSUE THREAD

**Issue by bluelupo** [KristhianX/essential-buttons-toolbar#24]
If I enter the value "blank.html" in the settings for "New Tab URL", the Android browser Firefox does not display the expected blank page, but an error message that the page not exists.This error occurs when I press the "+" button.

Greetings
Michael

**Comment by KristhianX** [comment]
Hi Michael, thanks for your feedback!

On the settings page, you need to paste the entire URL for 'blank.html.' You can obtain it by opening the help message next to the homepage URL label and holding the link to copy the URL.

**Comment by bluelupo** [comment]
Hello Kristhian,
Thanks for the quick reply. OK, so now I get a blank page. It would be even better if I could immediately open a new page, like from the standard menu (+ New Tab) of the Firefox app, e.g. to open a saved bookmark, is this possible with your addon?

Regards
Michael

**Comment by KristhianX** [comment]
Currently, that is not possible; add-ons cannot access the browser UI or bookmarks.

I am working on a homepage replacement for Firefox, where users can add their top sites. It is going to be included in the next update, hopefully next week. See issue #6 for more info.

Regards
