### ISSUE TITLE
Bug on Amazon Gaming

### ISSUE THREAD

**Issue by BlackSheepbe** [KristhianX/essential-buttons-toolbar#30]
Hi, today I found that the extension was causing gaming.amazon.com to not load properly, screen stays black. I tried disabling all other extensions but nothing worked, only disabling this one. 

I haven't seen this bug happening anywhere else for now.

**Comment by KristhianX** [comment]
Hi, thanks for reporting this issue. I will check why this is happening.

**Comment by KristhianX** [comment]
Hi! Sorry for the late reply. I'm working on the add-on again, and I've just submitted a fix. It will be available in the next update in a few days. Thanks for your report, and please feel free to report any other bugs.
