### ISSUE TITLE
[Request] Light mode for toolbar

### ISSUE THREAD

**Issue by emvaized** [KristhianX/essential-buttons-toolbar#34]
Toolbar currently is always shown in dark mode, making it stand out too much when the app is in light mode: 

![Screenshot_20240910_211637_Firefox](https://github.com/user-attachments/assets/02737e8c-e387-4651-b229-7a7219b1e3f1) 

I would love if it switched light/dark mode automatically depending on device dark mode status.

**Comment by KristhianX** [comment]
Hi! Thanks for your great suggestion!

It's something I’d like to include in the add-on. Unfortunately, I won’t have access to my computer (or time to try developing on my phone) for a few weeks, maybe longer.

I’m thinking of offering just three options: dark, light, and auto themes, to keep things simple.

If you have the time and would like to make a pull request for this, that would be great. In that case, I’d like to know what approach you plan to take beforehand. My main goal is to keep the add-on as fast and lightweight as possible.

**Comment by emvaized** [comment]
> If you have the time and would like to make a pull request for this, that would be great. In that case, I’d like to know what approach you plan to take beforehand. My main goal is to keep the add-on as fast and lightweight as possible.

Sorry, I don't think I will have time to make pull request for this anytime soon. But I think the best implementation would be to utilize CSS variables for background and foreground colors depending on user preference, and use `@media (prefers-color-scheme: *)` CSS selector for automatic switching. 

However, I'm not sure if such an option really needs manual customization. Probably it will be fine for now to just add automatic theme switching using [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme). And then see, if anyone would request an option to change theme manually at all. The majority of users probably will be happy if toolbar just blends well with Firefox's own toolbar and it's design, looking like an additional native toolbar.

**Comment by KristhianX** [comment]
Hi! This feature was added in version 1.8, which is already available on the AMO store. The system theme will now be automatically detected using `prefers-color-scheme`, as you suggested. Thanks!

**Comment by Siva981** [comment]
Hi,

Unfortunately, I'm a fan of the dark theme (even though I have my Firefox & Android themes set to light). I liked it the way it originally was & now it is too jarring for my eyes, with everything all white at the bottom of the screen. I had set the transparency to 0.5 when the theme was dark. And it was perfect for my use case.

Please give the users an option to choose between Light, Dark & System themes. The current method is forcing me to unwillingly stay with the Light theme, which I feel is rather counterintuitive. And I believe that more than a few users of EBTB would feel the same way.

In the meantime, while I wait for you to provide that option, I have reverted my Android's EBTB to Version 1.7.2 by downloading the xpi file from addons.mozilla.org & installing it after enabling the debug menu on my Firefox For Android. My eyes are better now for the time being, lol 😄

Please do the needful.

Thank you in advance!

**Comment by KristhianX** [comment]
Hi @Siva981 

Sure! It will be included in the next update. ;)
