### ISSUE TITLE
[Request] Toolbar position

### ISSUE THREAD

**Issue by Achyuth072** [KristhianX/essential-buttons-toolbar#36]
Is there any sort of way of changing the toolbar placement? I'm using another extension called Tablet UI which gives you tabstrips on android. The problem is that both bars are in same position. 

![Screenshot_2024-09-19-17-18-17-04_9c7ad408470e52983cc8816adf9ff347.jpg](https://github.com/user-attachments/assets/b85a1856-9119-451d-ba4e-0e6568ec72f5)

**Comment by KristhianX** [comment]
Hi! Thanks for your feedback! Sorry for the late reply.

In the add-on settings page, you can set the toolbar position to the top.

Issue #18 is very similar to this one, so I will close this as a duplicate. Please check the comments in that issue, and feel free to share your thoughts or suggestions.
