### ISSUE TITLE
[request] open home page in new tab

### ISSUE THREAD

**Issue by mashirozx** [KristhianX/essential-buttons-toolbar#38]
hope the new tab button and home button at the same time, thank you very much!

**Comment by KristhianX** [comment]
Hi! Thanks for your feedback, and sorry for the late reply. 

Could you please share more information about the behavior you expect from the buttons? I’m having trouble understanding.

**Comment by KristhianX** [comment]
Hi! Thank you for your kind words. I'm really glad to hear that you like the add-on.

What you described is the behavior of the "New Tab" button. In the settings page, set the new tab page URL to be the same as the homepage URL.

**Comment by KristhianX** [comment]
Hi! I'm closing this for now since there hasn’t been a reply. Feel free to add more comments about this or report other issues. Have a nice day!
