### ISSUE TITLE
The gesture bar is overlapping the toolbar

### ISSUE THREAD

**Issue by circcc** [KristhianX/essential-buttons-toolbar#39]
![Screenshot_20241020-142648 (1)](https://github.com/user-attachments/assets/15f198cd-14d3-4230-a8fe-eb347911f715)
3 button navigation bar mode have no problem,
but the gesture bar is overlapping the toolbar in swipe gesture mode(android 14).
please make a move up toolbar option.

**Comment by KristhianX** [comment]
Hi! Thanks for your feedback!

I think your suggestion is great. I'll add the option to create a gap at the bottom. I'll keep you updated on any changes. Thanks again!

**Comment by KristhianX** [comment]
Hi! I think this issue may be related to the Firefox app size. They have made some changes in recent updates. I've been testing this on my device and haven't encountered the issue. Could you please confirm if you are still experiencing this behavior? If so, please share the Firefox version you're using (e.g., beta, stable) along with the version number.

**Comment by circcc** [comment]
![Resize_20241111_030749_9697](https://github.com/user-attachments/assets/d83b558e-bfa8-4915-a4ad-f3762b9bcaf1)
132.0.1 stable latest version.

**Comment by KristhianX** [comment]
Thanks for your quick reply. I’ll add a setting to include a margin from the edge in the next update as a workaround.

**Comment by KristhianX** [comment]
Hi, the update is already available in the AMO store. Please let me know if you encounter any issues. Thanks for your feedback, and have a nice day!

**Comment by circcc** [comment]
![Resize_20241112_145421_1940](https://github.com/user-attachments/assets/25e338ae-6976-41b0-b8a2-4b03f010eafa)

Thanks, it works great!
