### ISSUE TITLE
FR: Vertical orientation on left or right side

### ISSUE THREAD

**Issue by quadcom** [KristhianX/essential-buttons-toolbar#40]
I find there's more content in pages either at the top or bottom that the bar interferes with. But normally, website has left and right margins that are clean whitespace. Having the option to have the toolbar on ether side would be a great addition I think.

Thanks for putting this out there! #

**Comment by KristhianX** [comment]
Hi! Thank you for your feedback. I was thinking the same, and now that you've suggested it, I feel even more motivated to give it a try. I'll add this option in the next update. Have a great day!

**Comment by KristhianX** [comment]
Hi, the update is already available in the AMO store. Please let me know if you encounter any issues. Thanks for your feedback, and have a nice day!
