### ISSUE TITLE
add a button to access "find in page"

### ISSUE THREAD

**Issue by mahela007** [KristhianX/essential-buttons-toolbar#41]
Thanks for making this addon! 
I do a lot of reading on my phone and using this addon helps a lot. I use "Find in page" a lot to quickly scan a article for relevant content, so having a button to quickly access Firefox's "find in page" with a single clock would be very useful!
Please consider adding this as a feature.

**Comment by KristhianX** [comment]
Hi @mahela007!

Thank you for your feedback and kind words—I’m really glad you find the add-on helpful.

Regarding your request, the API for add-ons in Firefox for Android isn’t as complete as the API support for desktop Firefox add-ons. Support for features like find, bookmarks, history, and more isn’t available. However, before concluding that it’s not possible, I’ll investigate any potential workarounds.

There’s also an existing request ( #12 ) to create an alternative 'find in page' feature to replace the browser’s integrated one.

**Comment by KristhianX** [comment]
After some research, I couldn’t find any workarounds, so this isn’t possible at the moment. It would need to be developed separately, as the browser-provided UI is not accessible.
