### ISSUE TITLE
Global listeners for each button except the settings

### ISSUE THREAD

**Issue by MilaMurry** [KristhianX/essential-buttons-toolbar#42]
The problem with Firefox is that there is no way to delete the localStorage upon exiting the browser / closing a tab thus eating up unnecessary spaces so some kind of listeners would be good.  I'd like to make a userscript to fix that. So something like this:

```javascript
// @match        *://*/*
// @run-at       document-start

(function() {
  'use strict';
  
  if (window.essBtnsToolbar) {
    
     const ebt =  window.essBtnsToolbar;
     delete window.essBtnsToobar; // Some sites like to meddle with unnecessary things.

     // Other stuff here like is it ready yet? do we need to delete the storage for this site? and etc...
     //if (ebt.isReady) ...

     ebt.beforeCloseTabListener = function() {
        // Get variables, check variables, etc...
     };
     ebt.afterCloseTabListener = function() {
        console.log('After clicked');
        localStorage.clear(); // It might be too late doing it here.
     };

     // I may need to use this function.
     GM_addValueChangeListener('variable', callback);
  }
})();
```

**Comment by KristhianX** [comment]
If I understand correctly, you are concerned that the website accesses the settings of the toolbar from localStorage. Is that correct? If so, the toolbar does not use localStorage; some settings are saved to browser.storage.local and others to browser.storage.sync. These are only visible to the add-on.

**Comment by MilaMurry** [comment]
No, no, no... that's not what I meant. Well you know every website can have their own localStorage. When you're using a search engine, you'll probably gonna visit a lot of sites and you'll end up with tens/hundreds of localStorages. Over time, you would probably have thousands of them and that's the problem. So having listeners like `document.onunload` or `window.onclick` would be fantastic.

My use case would be to delete website's localStorage that I don't want upon closing/exiting a website. You know it is about storage, trackings and privacy.

**Comment by MilaMurry** [comment]
No, no, no... that's not what I meant. Well you know every website can have their own localStorage. When you're using a search engine, you'll probably gonna visit a lot of sites and you'll end up with tens/hundreds of localStorages. Over time, you would probably have thousands of them and that's the problem. So having listeners like `document.onunload` or `window.onclick` would be fantastic.

My use case would be to delete website's localStorage that I don't want upon closing/exiting a website. You know it is about storage, trackings and privacy.

**Comment by KristhianX** [comment]
Oh, so you want something like the Cookie AutoDelete extension, but for localStorage. That sounds like a great idea for a new extension dedicated specifically to that function. I did some research and found one called Flush Site Data ( https://addons.mozilla.org/en-US/firefox/addon/flush-site-data/ ), which seems to perform that task on demand. However, it is not available for Android.

Details about the code that add-on uses can be found here:  
https://github.com/mk-fg/waterfox#flush-site-data

Please take a look and let me know your opinion.

**Comment by MilaMurry** [comment]
Yes exactly and none of them worked for Android. The problem with that addon and others is that you have to click to trigger them and they won't clear the localStorages either. What a bummer.  Easier if I could do something when clicking the "Close tab" and "Close all tabs" buttons. Feel free to close the issue if you don't feel doing it. Cheers

**Comment by KristhianX** [comment]
I think that if any additional configurations are needed (such as sites to whitelist, stats, or other settings), it would be better to implement it in a separate add-on. Additionally, if I add an option to clear the localStorage, there should also be options to clear other data, similar to the add-on I mentioned in my previous comment. Personally, I don't use add-ons to clear cookies or similar data, as I tend to stick to the same sites. Therefore, I'm not very familiar with the expected functionalities of such add-ons.

I will close this as 'not planned' for now, but I’ll try to learn more about this topic. Thank you for your suggestion.
