### ISSUE TITLE
Icons disappear on new integrated homepage

### ISSUE THREAD

**Issue by zythra** [KristhianX/essential-buttons-toolbar#44]
I love the new integrated homepage!  I have discovered an issue with icons disappearing though.

Steps to reproduce:

1. Create multiple icons
2. Go into "move mode"
3. Move an icon to a new location in the layout
4. Exit "move mode"
5. Tap the home button
6. The icon that was moved is gone

For now I have gotten around this issue by exporting the json file, manually editing it, and then importing the modified version.

**Comment by KristhianX** [comment]
Hi! I’m glad to hear that you like the new homepage.

I couldn’t reproduce the issue following the steps you provided. Could you please create a list of random top sites (e.g., name: kkkk, URL: kkkk) and record the issue?

Also, let me know which Firefox variant you’re using (Stable, Beta, Nightly) and its version number. 

Thanks for your feedback!

**Comment by zythra** [comment]
You bet.  I've attached a recording where I create 2 sites, rearrange them, and then click home.  You'll see that both sites disappear.

I'm on nightly 135.0a1.

Thanks!

https://github.com/user-attachments/assets/adc04dbd-0a2e-4e53-85b0-c6da103ca98f

**Comment by KristhianX** [comment]
Wow, you’re fast! Thanks. I was just editing my comment to say that I was able to reproduce it as well. I’ll take a look—thanks for your feedback!

**Comment by KristhianX** [comment]
The fix for this bug has been added in version 1.9.1. I will close this issue now. Thank you again for the report, and please feel free to report any other issues.
