### ISSUE TITLE
Icon layout suggestions for the new integrated homepage

### ISSUE THREAD

**Issue by zythra** [KristhianX/essential-buttons-toolbar#45]
The new integrated homepage is something I've wished for in the Android version of Firefox for a long time!  Thank you so much for adding this to your extension!

I have a couple of quality of life suggestions for the layout, they aren't deal breakers at all, just nice to haves.

1. Allow the user to select how many icons are allowed per row, similar to most Android launchers.  It would be nice to be able to have more than 4 per row.
2. Allow the user to adjust the size of the icons

The above to could potentially be the same.  I don't know what type of layout rendering you're using, but if it's a responsive layout then allowing the user to select the number of icons per row (within a reasonable minimum and maximum range) would handle the resizing automatically.

Thanks for an awesome extension!  😊

**Comment by KristhianX** [comment]
Thanks for the suggestions and kind words!

The size of the top sites will be editable in the next update.

The layout currently depends on the screen size—if you switch to landscape mode, you’ll see more columns but fewer rows.

**Comment by MilaMurry** [comment]
Hello there. Just updated to 1.9.1. Would you consider make text smaller. Im using the max size available which is 120 and most of the text are truncated. Can I have 0 paddings for the icons as well? Thank you.

**Comment by KristhianX** [comment]
This has been partially addressed in the new 1.9.1 version.

> Allow the user to select how many icons are allowed per row, similar to most Android launchers. It would be nice to be able to have more than 4 per row.

Instead of providing an option to specify the number of rows and columns, I chose to offer a combination of options to set the item size and the spacing between items. Adjusting these two options should allow users to achieve more or fewer rows/columns. Please let me know how well this approach works—does it produce the expected results?

I think adding a third option (item size, vertical spacing, and horizontal spacing) could make the customization even more precise.

**Comment by KristhianX** [comment]
> Hello there. Just updated to 1.9.1. Would you consider make text smaller. Im using the max size available which is 120 and most of the text are truncated. Can I have 0 paddings for the icons as well? Thank you.

Hi @MilaMurry! 

Sure, I can add a setting to specify the font size. It's recommended to use short names for the items, as longer names will be truncated, as you mentioned, and the text is limited to one line.

I can also allow the spacing to be set to 0 in the next update. Would you like the border radius to be disabled if the spacing is 0? Otherwise, I think it might look odd with small gaps at the corners of the items.

Also, do you think 120px is sufficient, or would you prefer the item size to be larger?

**Comment by zythra** [comment]
> This has been partially addressed in the new 1.9.1 version.
> 
> > Allow the user to select how many icons are allowed per row, similar to most Android launchers. It would be nice to be able to have more than 4 per row.
> 
> Instead of providing an option to specify the number of rows and columns, I chose to offer a combination of options to set the item size and the spacing between items. Adjusting these two options should allow users to achieve more or fewer rows/columns. Please let me know how well this approach works—does it produce the expected results?
> 
> I think adding a third option (item size, vertical spacing, and horizontal spacing) could make the customization even more precise.

I think what you added in 1.9.1 is perfect for what I was requesting, thank you!  Feel free to close my request.  😊

**Comment by MilaMurry** [comment]
@KristhianX 

> Would you like the border radius to be disabled if the spacing is 0? Otherwise, I think it might look odd with small gaps at the corners of the items.

Would be good to have it and not have it. Diff people diff taste. Im fine as it is now.

> Also, do you think 120px is sufficient, or would you prefer the item size to be larger?

Its fine but it would be good if it follows browser's theme. The spacings, icons size, text need a little adjustments I think. Here look at this pic

![pic](https://github.com/user-attachments/assets/993f0969-0e9d-4bf0-9db4-3ca2f9e1d918)

**Comment by KristhianX** [comment]
Hi @MilaMurry! 

Thanks for sharing your screenshot. As you mentioned, it would be better to let users decide the size of the top sites container (reducing the size of the gaps at the edges). Especially if the user doesn't set a wallpaper, there’s no point in having empty spaces around the container.

I will add an option to specify the container's width and height, and I’ll ensure the title grows consistently with the top sites' size so it won’t be smaller than the top sites' titles.

I’ll mark this issue as complete once these changes are implemented. Any other suggestions can be submitted as separate issues.

**Comment by KristhianX** [comment]
Hi @MilaMurry!

The new version 1.9.2 is now available on the store. It includes the option to change the container's width and height, as well as the text size. Oh, and there's also a new toolbar button to add the top sites! It will prefill the name and URL based on the current tab's properties.

I’ll close this issue now as completed. Please don't hesitate to report any problems by opening a new issue. Have a great day!

**Comment by MilaMurry** [comment]
@KristhianX Superb. Thank you and Merry Christmas. May God bless you.
