### ISSUE TITLE
Open addon's page from shortcuts

### ISSUE THREAD

**Issue by MilaMurry** [KristhianX/essential-buttons-toolbar#46]
Easier to edit uBlock filters and Violentmonkey scripts. Currently it does nothing. The urls may look like these:
***Ublock***
```
moz-extension://f68d8744-6312-48be-b36e-f9913646ee30/dashboard.html#1p-filters.html
```

***Violentmonkey***
```
moz-extension://741dade3-3af6-426e-9af1-f65bb2ec1c6a/options/index.html
```

**Comment by KristhianX** [comment]
Hi! 

That is correct, the browser does not allow opening other add-on pages from there, but they can be opened by using `browser.tabs.update` instead.

I've already added the code for that. It will check if the link starts with `moz-
extension://` and use the correct method. If the link does not, it will open the link as usual.

**Comment by KristhianX** [comment]
Added in commit 1d51000.

**Comment by MilaMurry** [comment]
Wow. Thats pretty quick. I'll assume it is done. Thanks again and happy new year.

**Comment by enlomaloperverso** [comment]
moz-extension://f68d8744-6312-48be-b36e-f9913646ee30/dashboard.html#1p-filters.html
