### ISSUE TITLE
Tabs created by the toolbar in private browsing are not private tabs.

### ISSUE THREAD

**Issue by KristhianX** [KristhianX/essential-buttons-toolbar#5]
Tabs created using the `tabs.create()` function in private browsing are default tabs, not private tabs.

**Steps to Reproduce:**
1. Enable Run in private browsing.
2. Open private browsing mode.
3. Use the toolbar to create tabs, duplicate tabs, etc.
4. Check the browsing history for unwanted traces.

**Expected Behavior:**
Tabs created in private browsing mode should be private tabs.

**Comment by KristhianX** [comment]
Version 1.6.2 has been released with `"incognito": "not_allowed",` in manifest.json to prevent the add-on from working in private browsing.

**Comment by Lurgainn** [comment]
> Version 1.6.2 has been released with `"incognito": "not_allowed",` in manifest.json to prevent the add-on from working in private browsing.

Hello,
I generally surf the web using "incognito" mode, so this has a big impact on me. I hope that this is a temporary choice to wait for the fix of this bug.
I don't want to pressure you, but have you any idea about the timing of the fix, so you can allow again the incognito mode? I would even prefer to have the incognito mode again with the bug, maybe with a warning popup that says that the new tab will not be in incognito mode.
Anyway thanks for your work: your addon is very useful

**Comment by KristhianX** [comment]
> > Version 1.6.2 has been released with `"incognito": "not_allowed",` in manifest.json to prevent the add-on from working in private browsing.
> 
> Hello, I generally surf the web using "incognito" mode, so this has a big impact on me. I hope that this is a temporary choice to wait for the fix of this bug. I don't want to pressure you, but have you any idea about the timing of the fix, so you can allow again the incognito mode? I would even prefer to have the incognito mode again with the bug, maybe with a warning popup that says that the new tab will not be in incognito mode. Anyway thanks for your work: your addon is very useful

Hi, thanks for your feedback. I have not found any workaround to this problem. I am thinking of disabling the create new tab button when it is in incognito mode. I will need to test the other buttons to see if there are any unwanted behaviors. The ideal fix will depend on Firefox developers improving the API for mobile add-ons. I have been busy lately and have not made any updates. I cannot give you a precise date, but I do want to keep supporting the add-on, so I will try to make some time for it in the next few weeks. What do you think about having the toolbar with the create new tab button deactivated?

**Comment by Lurgainn** [comment]
> What do you think about having the toolbar with the create new tab button deactivated?

Hi,
In this regard, I think it's a good choice. Your additional component is so useful for all other features that to lose the new tab button in incognito mode is certainly an acceptable compromise.

Thanks again for your effort.

**Comment by Lurgainn** [comment]
> What do you think about having the toolbar with the create new tab button deactivated?

After my previous post I thought: Firefox's API would allow you to add a button that opens the list of bookmarks? And if yes, if in incognito mode you open a new bookmark from this button, would the tab also open in incognito mode?
If yes, this would be a new beautiful function that could largely overcome the lack of the new tab button.

If all this is not feasible, then I remain of the opinion that I had said in the previous post.

**Comment by KristhianX** [comment]
> > What do you think about having the toolbar with the create new tab button deactivated?
> 
> After my previous post I thought: Firefox's API would allow you to add a button that opens the list of bookmarks? And if yes, if in incognito mode you open a new bookmark from this button, would the tab also open in incognito mode? If yes, this would be a new beautiful function that could largely overcome the lack of the new tab button.
> 
> If all this is not feasible, then I remain of the opinion that I had said in the previous post.

Sadly, the API does not allow opening the bookmarks list.

Thanks for your suggestion and for your answer. I'll notify you when I enable the add-on in incognito mode again.

Please let me know if you have any other suggestions or issues with the add-on. Have a nice day.

**Comment by Lurgainn** [comment]
> Thanks for your suggestion and for your answer. I'll notify you when I enable the add-on in incognito mode again.

Thanks so much.

**Comment by Lurgainn** [comment]
Sorry to bother you, but are there any news about the enabling of this addon in incognito mode? Thanks again

**Comment by KristhianX** [comment]
Hi!

Thanks for the reminder. I had some time to work on this. Sadly, the API has not been fixed, so it is not possible to create incognito tabs or windows from the add-on. However, I removed the "incognito": "not_allowed" line from manifest.json. Now it is possible to have the toolbar on private tabs with the following changes:

    Any button that creates a tab won’t be available.
    The toolbar background color will change to purple to better indicate that the current tab is indeed private.

If you see the toolbar with the normal background color in private mode, you should close such a tab since it is not private. In my tests, this only happens if you go to the browser menu and, under Extensions, you open this add-on. The settings page that opens in this way is not a private tab. I did not test if this is the case with other add-ons. If you go to Extensions Manager, select this add-on, and then click the Settings button, it will correctly open the settings page in a private tab. So if you change the tab URL, it should continue to be private.

Buttons disabled in incognito mode are: "New tab", "Duplicate tab", "Settings", "Undo close tab(s)", "Close all tabs", and "Close other tabs". This is because they will also close tabs in the normal mode, which is unwanted behavior.

The update will be available in a few hours. I have to write the changelog.

Please feel free to report any issues with these changes or suggestions. Thanks for using the add-on and helping to improve it.

Have a nice weekend.

**Comment by KristhianX** [comment]
Closing this issue for now, as it is currently not possible. Add-ons for Firefox on Android cannot create private tabs.
